AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for ca-geo-corona App.  
Parameters:
  ENV:
    Type: String
  DBHOST:
    Type: String
  DBNAME:
    Type: String
  DBUSER:
    Type: String
  DBPASS: 
    Type: String
  WEBHOOK:
    Type: String
  TOKEN:
    Type: String

Globals:
  Function:
    Timeout: 900
    Environment: 
      Variables:
        ENV: !Ref ENV
        DBHOST: !Ref DBHOST
        DBNAME: !Ref DBNAME
        DBUSER: !Ref DBUSER
        DBPASS: !Ref DBPASS
        WEBHOOK: !Ref WEBHOOK
        TOKEN: !Ref TOKEN

Resources:
  # FacilityRegisterAutomaticallyFunction:
  #   Type: AWS::Serverless::Function 
  #   Properties:
  #     Role: arn:aws:iam::880843126767:role/go-academy-lambda
  #     CodeUri: facility-register-automatically/
  #     Handler: facility-register-automatically
  #     Runtime: go1.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       CatchAll:
  #         Type: Api 
  #         Properties:
  #           Path: /facility/register/automatically
  #           Method: GET
  #           RestApiId: !Ref CaGeoCoronaAPI

  # FacilityRegisterManuallyFunction:
  #   Type: AWS::Serverless::Function 
  #   Properties:
  #     Role: arn:aws:iam::880843126767:role/go-academy-lambda
  #     CodeUri: facility-register-manually/
  #     Handler: facility-register-manually
  #     Runtime: go1.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       CatchAll:
  #         Type: Api 
  #         Properties:
  #           Path: /facility/register/manulally
  #           Method: GET
  #           RestApiId: !Ref CaGeoCoronaAPI

  # FacilityGetFunction:
  #     Type: AWS::Serverless::Function 
  #     Properties:
  #       Role: arn:aws:iam::880843126767:role/go-academy-lambda
  #       CodeUri: facility-get/
  #       Handler: facility-get
  #       Runtime: go1.x
  #       Architectures:
  #         - x86_64
  #       Events:
  #         CatchAll:
  #           Type: Api 
  #           Properties:
  #             Path: /facility
  #             Method: GET
  #             RestApiId: !Ref CaGeoCoronaAPI
  #             RequestParameters:
  #               - method.request.querystring.prefName
  #               - method.request.querystring.cityName

  #クエリで指定する日付、都道府県のデータをデータベースに登録する
  InfectionStatusRegisterFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Role: arn:aws:iam::880843126767:role/go-academy-lambda
      CodeUri: infection-status-register/
      Handler: infection-status-register
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /infectionStatus/register
            Method: GET
            RestApiId: !Ref CaGeoCoronaAPI
            RequestParameters:
              - method.request.querystring.date
              - method.request.querystring.prefecture

  #日次で昨日の感染者数データを感染対策サイトから取得し、データベースに登録する
  InfectionStatusRegisterScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::880843126767:role/go-academy-lambda
      CodeUri: infection-status-register-schedule/
      Handler: infection-status-register-schedule
      Runtime: go1.x
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(30/20 2 * * ? *) 
  
  #昨日を起点に1週間遡って、感染者数のデータをデータベースから取得し、画像生成、Slack通知を行う
  # InfectionStatusNotifyScheduleFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Role: arn:aws:iam::880843126767:role/go-academy-lambda
  #     CodeUri: infection-status-notify/
  #     Handler: infection-status-notify
  #     Runtime: go1.x
  #     Events:
  #       ScheduleEvent:
  #         Type: Schedule
  #         Properties:
  #           Schedule: cron(30/20 2 * * ? *)

  # (デバッグ用API）
  InfectionStatusNotifyScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::880843126767:role/go-academy-lambda
      CodeUri: infection-status-notify/
      Handler: infection-status-notify
      Runtime: go1.x
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /infectionStatus/notify
            Method: GET
            RestApiId: !Ref CaGeoCoronaAPI

  InfectionStatusGetFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Role: arn:aws:iam::880843126767:role/go-academy-lambda
      CodeUri: infection-status-get/
      Handler: infection-status-get
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /infectionStatus/{type}
            Method: GET
            RestApiId: !Ref CaGeoCoronaAPI
            RequestParameters:
              - method.request.path.type
              - method.request.querystring.date
              - method.request.querystring.prefecture


  CaGeoCoronaAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: false

Outputs:
  InfectionStatusRegisterFunction:
    Description: "Type API"
    Value: !Sub "https://${CaGeoCoronaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/infectionStatus/register/"
  InfectionStatusRegisterScheduleFunction:
    Description: "Type Events Schedule"
    Value: !Sub "https://${CaGeoCoronaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod//infectionStatus/register/schedule"
  InfectionStatusGetFunction:
    Description: "Type API"
    Value: !Sub "https://${CaGeoCoronaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/get"    
